# This is a basic workflow to build and deploy a React app to GitHub Pages
name: Deploy GitHub Pages

# Controls when the workflow will run
on:
  # Runs on pushes targeting the default branch
  push:
    branches: [master, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# Set environment variables
env:
  # Use folder for React app
  FOLDER: ./Scrolling

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Builds the React app
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Setup defaults for the steps within a job
    defaults:
      run:
        working-directory: ${{ env.FOLDER }}

    # Setup matrix for OS and NodeJS
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [19.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0

      # Enable Pages
      - name: Setup Pages
        uses: actions/configure-pages@c5a3e1159e0cbdf0845eb8811bd39e39fc3099c2 # v2.1.3

      # Setup NodeJS on runner
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      # Build the React app (npm install)
      - name: npm ci, build and test
        run: |
          npm install
          npm ci
          npm run build --if-present

      # Upload package-lock.json
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /home/runner/work/react-gh-pages/react-gh-pages/Scrolling/package-lock.json

      # Upload artifact (gzip) to deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@253fd476ed429e83b7aae64a92a75b4ceb1a17cf # v1.0.7
        with:
          path: ${{ env.FOLDER }}/build

  # Deploy app to Github Pages
  deploy:
    # Setup env variables for the job
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Define dependency's between jobs
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Deploy to Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@20a4baa1095bad40ba7d6ca0d9abbc220b76603f # v1.2
